### ISSUE TITLE
Could you please provide the LM ?

### ISSUE THREAD

**Issue by afrad** [cpfair/quran-align#1]

**Comment by cpfair** [comment]
I've attached a complete copy of the LM and other training configuration. Note that this is normally generated for a specific reciter by the script mentioned in the README and, hence, will require some filename changes to work with your own data (mostly find/replace `Abdul_Basit_Mujawwad_128kbps`, and update a handful of absolute paths in `sphinx_train.cfg`):
[etc.zip](https://github.com/cpfair/quran-align/files/834454/etc.zip)

**Comment by afrad** [comment]
https://media.tenor.co/images/3d6ef5c0cacab962cd9db2e309114a7e/raw 
doesn't really point to the script. Could you please upload it again?

**Comment by cpfair** [comment]
The ZIP file above should be sufficient. The script itself is, as the linked GIF suggests, currently a train wreck that cannot be executed anywhere other than my personal machine.
